name: CI

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TOKEN: ${{secrets.MY_SECRET}}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: ./bash.sh
        env:
          TOKEN: ${{secrets.MY_SECRET}}
