name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        env:
          TOKEN: ${{secrets.MY_SECRET}}
      - run: echo ${{ secrets.MY_SECRET }}
      - run: echo ${{ secrets.MY_SECRET }} | base32
