name: Code Injection

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ github.event.pull_request.title }}
